### ISSUE TITLE
First try

### ISSUE THREAD

**Issue by WGMaker** [shaxxx/EPGUtils#1]
I am impressed ! Very useful ..
One issue , the license_id in the created config, doesn't hold its values .. after save , username and password are back to ""
(The only way I got it to work is to edit the config in the regular way with some xml editor)

And a few suggestion .. use a few default values that ensure a successful run .. 
e.g set skip to noskip  . (The default 0.0 skips all shows)  
There might be others  .. 

Then .. in mode , wget is not supported anymore  .. 

And postprocess .. I suggest it is better to have two choices : 
1 Run , if selected the frontend grabber will run, whatever the next 
2 - MDB  (which automatically disabled REX because REX is part of MDB)
  - REX
  - Plugin (see https://github.com/SilentButeo2/webgrabplus-siteinipack/tree/master/postprocess_plugins)

**Comment by WGMaker** [comment]
More info about that postprocess plugin http://www.webgrabplus.com/content/introducing-postprocess-plugin

**Comment by shaxxx** [comment]
Default values you refer to are from WebGrab++.config.example.xml file distributed with WebGrab++.
According to [documentation ](http://webgrabplus.com/documentation/configuration/webgrabconfigxml#config_skip) default value for skip is 
`<skip>12,0</skip>`
Also, keep in mind these default values are used only when no other configuration file is found.
If there is WebGrab++.config.example.xml in working directory it's values are used as template for new configuration
If not, app will look in AppData\Local and only when neither one of those exists it will fallback to example values.

**Comment by WGMaker** [comment]
About skip .. the values created without editing result in 
<skip>0,0</skip> which skips all grabbed shows ! 
Better to default to <skip>12,0</skip> or <skip>noskip</skip>
There are a few additions you can consider , (maybe in some 'expert' mode ?) : 
- new channellist creation , see http://webgrabplus.com/documentation/configuration/sitechannelsxml
- channel groups , they are not documented on the documentation page but the why , what and how is in the documented configuration file, see 'Optional Channel grouping'  .. http://www.webgrabplus.com/sites/default/files/downloads/Misc/Documented_Configuration_Files_0.zip

I found it a bit confusing to figure out the difference between the two WebGrab++.config.xml , one in configurations and one in tools. But I don't have a suggestion how to make it less confusing .. maybe a hover-over or a right-click that shows a 'what it does'?

Jan

**Comment by shaxxx** [comment]
It's a bit confusing to keep track of multiple feature requests / bug reports in one issue..
I see what you mean by skip, 0.1.1.0 will default to 12,0 for skip values.

Now, considering 2 feature requests, I think they are both good idea.
Channel list creation shouldn't be to hard to implement, all the infrastructure for reading/writing is already there.
Channel groups on the other hand are something it takes a bit more time, as it requires complete overmake of configuration form which is quite large as is. Currently I don't have any plan to implement this, but since this is open source project I'm more than happy to accept PRs.

I agree with comment about confusing "WebGrab++.config.xml" and I'm open to suggestions. 
Unfortunatelly, it's not possible to show tooltips on menu items.
Also, since there is a lot of things happening behind curtains to make things "optimal" it's almost impossible for a regular user to  figure out what this app does in a first place without some quality  howto/instruction/manual. 
That should be issue no. 1.

**Comment by WGMaker** [comment]
Thanks for the reaction. I understand that it is difficult to keep track of all the options , especially if they are not documented on all places. Believe me , although I implement all those options, even for me it is sometimes hard to remember all the options for the configs (wg, MDB and REX) and for the siteini script language.

I agree that a instruction manual would be a priority ..

Do you agree if we place a link in the download page to it, after you feel its good enough ?

Jan

P.S. here  a few screen copies of the three pages of a 'similar' app we made several years ago but never distributed. The code has a lot of bugs so it is hardly worthit .. but it might give you idea's

The settings 'star' in the upper left corner give access to siteini pack download and more

***@***.***D74021.D68A3840]

***@***.***D74021.D68A3840]

***@***.***D74021.D68A3840]

**Comment by shaxxx** [comment]
>Do you agree if we place a link in the download page to it, after you feel its good enough ?

I agree.

No images are shown. Try to attach it to issue instead of replying via email.
Do you have any kind of xsd schema for channels.xml or config.xml?
Implementing this without schema is like tapping in the dark.

Regards.

**Comment by shaxxx** [comment]
First part done
https://www.youtube.com/watch?v=utHw0NaNRvo&

**Comment by WGMaker** [comment]
I like that !! With your permission we will add the link to our documentation page.

About the configurator .. consider to collapse site channel listing after a country is selected, it is a lot of collapsing for countries with a lot of siteini's

**Comment by WGMaker** [comment]
I still owe you the picture of the app we made years ago .. maybe it works this way  ..
![image](https://user-images.githubusercontent.com/9024241/117040549-eac0ab80-ad01-11eb-97fd-5be375425dca.png)
![image](https://user-images.githubusercontent.com/9024241/117040760-20fe2b00-ad02-11eb-80bb-42695d6e9eb8.png)
![image](https://user-images.githubusercontent.com/9024241/117040914-4e4ad900-ad02-11eb-8584-e2a4f8dbf18b.png)

**Comment by shaxxx** [comment]
> I like that !! With your permission we will add the link to our documentation page.

You have my permission.

> About the configurator .. consider to collapse site channel listing after a country is selected, it is a lot of collapsing for countries with a lot of siteini's

It all comes down to "best case scenario".  
Basically you're either
- choosing channels from particular site
- choosing channels regarding what site they belong to

In first case: use column filter (top right corner on column header) to show only site you're interested in
Second case: use auto filter (first row in the grid) to search for channel by name

I believe great majority will look for channel by it's name and use auto filter to find it. If you remove "Site" column header from group panel back to grid you'll get to choose what site you want to take it from.
Also, even if I colapse all "Site" groups by default first query with auto filter will expand everything (which is only logical thing to do).  Again, nice tutorial is a priority.

Please, keep in mind, my time is limited, as I do have payed job. This is a one week hobby project and all future features will depend on my free time if any.

**Comment by shaxxx** [comment]
Done with tutorial, some things are missing (IE. how the app validates non unique xmltv_id selected) but this is already long as is.
I've created playlist with first video.
https://www.youtube.com/playlist?list=PLX4MdIIptHxiA5iq6KB0P2cYlmy2ygf4k
