### ISSUE TITLE
XML error

### ISSUE THREAD

**Issue by UragonElite** [shaxxx/EPGUtils#2]
There is an error box when creating a New Configurations
it says," Failed to create user configuration.There is an error in XML document (1, 1).

How to fix this pls?

**Comment by shaxxx** [comment]
One of xml files is invalid, this can be either WebGrab configuration or one of site.xml files.
You can copy suspicious XML file to some online validator, IE. https://www.xmlvalidation.com/
Also, you can edit ConfigMaker.log4net and change
`<level value="INFO" />` to `<level value="ALL" />` then delete ConfigMaker.log file, restart ConfigMaker.exe, reproduce the error in the app and then attach the log file here.
Maybe it will give better idea what XML is invalid.

**Comment by shaxxx** [comment]
Closed due to lack of response
