### ISSUE TITLE
Edit webgrab config error

### ISSUE THREAD

**Issue by bebawy6** [shaxxx/EPGUtils#3]
Hello,
when trying to edit webgrab config it gave an error. it looks like it is reading from your PC configuration (C:\Users\isako\source\repos\EPGUtils\ConfigMaker\***) please see attached log file. I am using your new version 0.2.3.0 and same issue in the previous version also.

another ask, is there is any chance to add option to combine multiple xml file together in one file using your amazing app I found utility in one of the sites created by Kerry Mitchell combine two xml files together. see link

https://forum.team-mediaportal.com/threads/us-epg-using-zap2xml-with-2-sources.137805/

thanks

[ConfigMaker.log](https://github.com/shaxxx/EPGUtils/files/7023441/ConfigMaker.log)

![002](https://user-images.githubusercontent.com/71897043/130277165-b6c77fe9-5974-4c32-b2d5-61f879333db3.JPG)

![001](https://user-images.githubusercontent.com/71897043/130277166-fec269ff-e548-433e-b155-407a48b64eda.JPG)

**Comment by shaxxx** [comment]
Debug info always reflects original build path, that doesn't mean it actually tries to read from it.

Looks like there's something wrong with your config.
Error is at line
https://github.com/shaxxx/EPGUtils/blob/7548b8a63f2d43a58836ca2ab94db4f06893507b/ConfigMaker/WebGrabConfigForm.cs#L108
making me think something in your postprocessing configuration is wrong.
Can you attach your config (edit private data first)?

**Comment by bebawy6** [comment]
you are correct my original webgrab config get change look for attach 

change the extension to allow upload

[WebGrab++.config.txt](https://github.com/shaxxx/EPGUtils/files/7023584/WebGrab%2B%2B.config.txt)

another ask, is there is any chance to add option to combine multiple xml file together in one file using your amazing app I found utility in one of the sites created by Kerry Mitchell combine two xml files together. see link

https://forum.team-mediaportal.com/threads/us-epg-using-zap2xml-with-2-sources.137805/

**Comment by shaxxx** [comment]
Your postprocess directive is invalid.
It's missing value.
It can have value "mdb" or "rex"
Please see http://webgrabplus.com/documentation/configuration/webgrabconfigxml#config_postprocess
Or you can simply remove this line if you're not doing any postprocessing.

Merging XMLs can be done with other utilites, or you can add all channels to one WebGrab configuration.
This is out of scope of this app.

**Comment by bebawy6** [comment]
many thanks for your time it works fine when add rex 
but the one I have is to add logos and i got the instruction to use it like the following from Jan van Straaten it consider custom postprocess 
<postprocess grab="y" run="y">C:\Users\A\AppData\Local\WebGrab+Plus\postprocess_plugins\add-logo\add_logo.exe /in=C:\data\Temp_EPG\arEPG1.v1.xml /out=C:\data\Temp_EPG\arEPG1.v1+logos.xml /logos=C:\Users\A\AppData\Local\WebGrab+Plus\siteini.pack\my_logos.ini </postprocess>
